version: '3'

networks:
    unicorn-nginx-php82-mysql8:

services:
    # nginx
    # nginx-service:        
    #     image: nginx:stable-alpine        
    #     container_name: unicorn-nginx-container
    #     ports:
    #         - "8081:80"
    #     volumes:
    #         - ./app:/var/www/project
    #         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #     depends_on:
    #         - php82-service
    #         - mysql8-service
    #     networks:
    #         - unicorn-nginx-php82-mysql8

    # php
    php82-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: unicorn-php82-container
        ports:
            - "9001:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - unicorn-nginx-php82-mysql8

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: unicorn-mysql8-container
        ports:
            - "5306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        networks:
            - unicorn-nginx-php82-mysql8

    mailer: #(same as email config)
        image: schickling/mailcatcher
        ports: ["1025", "1080"]
  #      networks:
  #          - unicorn-nginx-php82-mysql8